name: Push Workflow

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:

  # Validate HTML, CSS, JS + Security + Preview
  validate-site:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # List project files (debugging)
      - name: List project files
        run: ls -R

      #HTML Validation
      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Validate HTML
        run: htmlhint "**/*.html"

      #CSS Validation
      - name: Install Stylelint
        run: npm install -g stylelint stylelint-config-standard

      - name: Validate CSS
        continue-on-error: true #Prevents the whole process from halting when error is detected
        run: stylelint "**/*.css"

      #JS Validation
      - name: Install ESLint
        run: npm install -g eslint

      - name: Validate JavaScript
        continue-on-error: true 
        run: eslint "**/*.js" || true
        #ensures warnings don't break the workflow


      #security Scan for Secrets
      - uses: trufflesecurity/trufflehog@main
        with:
          path: .

      #Generates a preview website when merging
      - name: Create preview 
        uses: actions/upload-artifact@v4
        with:
          name: website-preview
          path: .
